
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DIPAK
 */
public class bookl extends javax.swing.JFrame {
    public static String selected_hotel=null;
    public static String code=null;
    /**
     * Creates new form bookl
     */
    public bookl() {
        initComponents();
        int r=0,g=0,b=0;
        float[] hsb=new float[3];
        r=14;
        g=140;
        b=214;
        logout.setBackground(Color.red);
        Color.RGBtoHSB(r, g, b, hsb);
        back.setBackground(Color.getHSBColor(hsb[0],hsb[1],hsb[2]));
        jPanel1.setBackground(Color.getHSBColor(hsb[0],hsb[1],hsb[2]));
        jPanel3.setBackground(Color.getHSBColor(hsb[0],hsb[1],hsb[2]));
        jPanel4.setBackground(Color.getHSBColor(hsb[0],hsb[1],hsb[2]));
        jPanel5.setBackground(Color.getHSBColor(hsb[0],hsb[1],hsb[2]));
        r=40;
        g=40;
        b=40;
        Color.RGBtoHSB(r, g, b, hsb);
        this.getContentPane().setBackground(Color.getHSBColor(hsb[0],hsb[1],hsb[2]));
        String a=location.place;
        splace.setText(a);
        int str=location.tr;
        trr.setText("Rooms req. : "+str);
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/oop?zeroDateTimeBehavior=convertToNull","root","12345");
            Statement s=con.createStatement();
            ResultSet rs=null;
            String name=null;
            rs=s.executeQuery("select name from logindata where active=1;");
            while(rs.next())
            {
                name=rs.getString(1);
            }
            sname.setText("Welcome "+name.toUpperCase());
            rs=s.executeQuery("select * from "+location.place+" order by price desc;");
            int i=1;
            String code;
            while(rs.next())
            {
                if(i==1)
                {
                    code=rs.getString(9);
                    hname1.setText(rs.getString(1));
                    nrate1.setText("Rated by : "+rs.getInt(5));
                    rate1.setText("Rating : "+rs.getFloat(4));
                    price1.setText("Price per night : "+rs.getInt(6)*str);
                    im1.setIcon(new ImageIcon(new javax.swing.ImageIcon("D:/photos/"+code+".jpg").getImage().getScaledInstance(195,130,Image.SCALE_SMOOTH)));
                }
                else if(i==2)
                {
                    code=rs.getString(9);
                    hname2.setText(rs.getString(1));
                    nrate2.setText("Rated by : "+rs.getInt(5));
                    rate2.setText("Rating : "+rs.getFloat(4));
                    price2.setText("Price per night : "+rs.getInt(6)*str);
                    im2.setIcon(new ImageIcon(new javax.swing.ImageIcon("D:/photos/"+code+".jpg").getImage().getScaledInstance(195,130,Image.SCALE_SMOOTH)));
                }
                else if(i==3)
                {
                    code=rs.getString(9);
                    hname3.setText(rs.getString(1));
                    nrate3.setText("Rated by : "+rs.getInt(5));
                    rate3.setText("Rating : "+rs.getFloat(4));
                    price3.setText("Price per night : "+rs.getInt(6)*str);
                    im3.setIcon(new ImageIcon(new javax.swing.ImageIcon("D:/photos/"+code+".jpg").getImage().getScaledInstance(195,130,Image.SCALE_SMOOTH)));
                }
                else if(i==4)
                {
                    code=rs.getString(9);
                    hname4.setText(rs.getString(1));
                    nrate4.setText("Rated by : "+rs.getInt(5));
                    rate4.setText("Rating : "+rs.getFloat(4));
                    price4.setText("Price per night : "+rs.getInt(6)*str);
                    im5.setIcon(new ImageIcon(new javax.swing.ImageIcon("D:/photos/"+code+".jpg").getImage().getScaledInstance(195,130,Image.SCALE_SMOOTH)));
                }
                i++;
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        im4 = new javax.swing.JPanel();
        sname = new javax.swing.JLabel();
        splace = new javax.swing.JLabel();
        trr = new javax.swing.JLabel();
        sort = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        price1 = new javax.swing.JLabel();
        hname1 = new javax.swing.JLabel();
        nrate1 = new javax.swing.JLabel();
        rate1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        im1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        price2 = new javax.swing.JLabel();
        hname2 = new javax.swing.JLabel();
        nrate2 = new javax.swing.JLabel();
        rate2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        im2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        price3 = new javax.swing.JLabel();
        hname3 = new javax.swing.JLabel();
        nrate3 = new javax.swing.JLabel();
        rate3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        im3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        price4 = new javax.swing.JLabel();
        hname4 = new javax.swing.JLabel();
        nrate4 = new javax.swing.JLabel();
        rate4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        im5 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        im4.setOpaque(false);

        javax.swing.GroupLayout im4Layout = new javax.swing.GroupLayout(im4);
        im4.setLayout(im4Layout);
        im4Layout.setHorizontalGroup(
            im4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        im4Layout.setVerticalGroup(
            im4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sname.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        sname.setForeground(new java.awt.Color(255, 255, 255));
        sname.setText("Welcome XYZ !");

        splace.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        splace.setForeground(new java.awt.Color(255, 255, 255));
        splace.setText("Place");

        trr.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        trr.setForeground(new java.awt.Color(255, 255, 255));
        trr.setText("Rooms Req:");

        sort.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        sort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Price : High to Low", "Price : Low to High", "Rating : High to Low", "Rating : Low to High" }));
        sort.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sortItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sort by :");

        back.setFont(new java.awt.Font("Caviar Dreams", 1, 48)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("←");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        price1.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        price1.setForeground(new java.awt.Color(255, 255, 255));
        price1.setText("Price per night :");

        hname1.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        hname1.setForeground(new java.awt.Color(40, 40, 40));
        hname1.setText("H_Name");
        hname1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hname1MouseClicked(evt);
            }
        });

        nrate1.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        nrate1.setForeground(new java.awt.Color(255, 255, 255));
        nrate1.setText("Rated by :");

        rate1.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        rate1.setForeground(new java.awt.Color(255, 255, 255));
        rate1.setText("Rating :");

        jLabel1.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 40, 40));
        jLabel1.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nrate1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rate1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hname1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(im1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hname1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nrate1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rate1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(im1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        price2.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        price2.setForeground(new java.awt.Color(255, 255, 255));
        price2.setText("Price per night :");

        hname2.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        hname2.setForeground(new java.awt.Color(40, 40, 40));
        hname2.setText("H_Name");
        hname2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hname2MouseClicked(evt);
            }
        });

        nrate2.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        nrate2.setForeground(new java.awt.Color(255, 255, 255));
        nrate2.setText("Rated by :");

        rate2.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        rate2.setForeground(new java.awt.Color(255, 255, 255));
        rate2.setText("Rating :");

        jLabel4.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 40, 40));
        jLabel4.setText("2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nrate2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rate2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(price2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hname2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(im2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hname2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nrate2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rate2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(im2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        price3.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        price3.setForeground(new java.awt.Color(255, 255, 255));
        price3.setText("Price per night :");

        hname3.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        hname3.setForeground(new java.awt.Color(40, 40, 40));
        hname3.setText("H_Name");
        hname3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hname3MouseClicked(evt);
            }
        });

        nrate3.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        nrate3.setForeground(new java.awt.Color(255, 255, 255));
        nrate3.setText("Rated by :");

        rate3.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        rate3.setForeground(new java.awt.Color(255, 255, 255));
        rate3.setText("Rating :");

        jLabel5.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(40, 40, 40));
        jLabel5.setText("3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nrate3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(rate3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(price3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hname3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(im3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hname3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrate3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rate3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(im3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        price4.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        price4.setForeground(new java.awt.Color(255, 255, 255));
        price4.setText("Price per night :");

        hname4.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        hname4.setForeground(new java.awt.Color(40, 40, 40));
        hname4.setText("H_Name");
        hname4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hname4MouseClicked(evt);
            }
        });

        nrate4.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        nrate4.setForeground(new java.awt.Color(255, 255, 255));
        nrate4.setText("Rated by :");

        rate4.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        rate4.setForeground(new java.awt.Color(255, 255, 255));
        rate4.setText("Rating :");

        jLabel6.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(40, 40, 40));
        jLabel6.setText("4");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(nrate4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(rate4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(price4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hname4, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(im5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hname4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nrate4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rate4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(im5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1541829391162 (1).png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(splace, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(sort, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(trr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout)
                        .addGap(10, 10, 10))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(splace)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sort, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hname1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hname1MouseClicked
        // TODO add your handling code here:
        selected_hotel=hname1.getText();
        String loc=location.place.toLowerCase();
        code=loc.substring(0,3);
        hotel_display x = new hotel_display();
        this.setVisible(false);
        x.setVisible(true);
    }//GEN-LAST:event_hname1MouseClicked

    private void sortItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sortItemStateChanged
        // TODO add your handling code here:
        String gett=(String)sort.getSelectedItem();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/oop?zeroDateTimeBehavior=convertToNull","root","12345");
            Statement s=con.createStatement();
            ResultSet rs=null;
            int i=1;
            if(gett.equals("Price : High to Low"))
            {
              rs=s.executeQuery("select * from "+location.place+" order by price desc;");  
            }
            else if(gett.equals("Price : Low to High"))
            {
              rs=s.executeQuery("select * from "+location.place+" order by price;");  
            }
            else if(gett.equals("Rating : High to Low"))
            {
              rs=s.executeQuery("select * from "+location.place+" order by rate desc;");  
            }
            else if(gett.equals("Rating : Low to High"))
            {
              rs=s.executeQuery("select * from "+location.place+" order by rate;");  
            }
            while(rs.next())
            {
                if(i==1)
                {
                    code=rs.getString(9);
                    hname1.setText(rs.getString(1));
                    nrate1.setText("Rated by : "+rs.getInt(5));
                    rate1.setText("Rating : "+rs.getFloat(4));
                    price1.setText("Price per night : "+rs.getInt(6)*location.tr);
                    im1.setIcon(new ImageIcon(new javax.swing.ImageIcon("D:/photos/"+code+".jpg").getImage().getScaledInstance(195,130,Image.SCALE_SMOOTH)));
                }
                else if(i==2)
                {
                    code=rs.getString(9);
                    hname2.setText(rs.getString(1));
                    nrate2.setText("Rated by : "+rs.getInt(5));
                    rate2.setText("Rating : "+rs.getFloat(4));
                    price2.setText("Price per night : "+rs.getInt(6)*location.tr);
                    im2.setIcon(new ImageIcon(new javax.swing.ImageIcon("D:/photos/"+code+".jpg").getImage().getScaledInstance(195,130,Image.SCALE_SMOOTH)));
                }
                else if(i==3)
                {
                    code=rs.getString(9);
                    hname3.setText(rs.getString(1));
                    nrate3.setText("Rated by : "+rs.getInt(5));
                    rate3.setText("Rating : "+rs.getFloat(4));
                    price3.setText("Price per night : "+rs.getInt(6)*location.tr);
                    im3.setIcon(new ImageIcon(new javax.swing.ImageIcon("D:/photos/"+code+".jpg").getImage().getScaledInstance(195,130,Image.SCALE_SMOOTH)));
                }
                else if(i==4)
                {
                    code=rs.getString(9);
                    hname4.setText(rs.getString(1));
                    nrate4.setText("Rated by : "+rs.getInt(5));
                    rate4.setText("Rating : "+rs.getFloat(4));
                    price4.setText("Price per night : "+rs.getInt(6)*location.tr);
                    im5.setIcon(new ImageIcon(new javax.swing.ImageIcon("D:/photos/"+code+".jpg").getImage().getScaledInstance(195,130,Image.SCALE_SMOOTH)));
                }
                i++;
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_sortItemStateChanged

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        location a =new location();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void hname2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hname2MouseClicked
        // TODO add your handling code here:
        selected_hotel=hname2.getText();
        String loc=location.place.toLowerCase();
        code=loc.substring(0,3);
        hotel_display x = new hotel_display();
        this.setVisible(false);
        x.setVisible(true);
    }//GEN-LAST:event_hname2MouseClicked

    private void hname3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hname3MouseClicked
        // TODO add your handling code here:
        selected_hotel=hname3.getText();
        String loc=location.place.toLowerCase();
        code=loc.substring(0,3);
        hotel_display x = new hotel_display();
        this.setVisible(false);
        x.setVisible(true);
    }//GEN-LAST:event_hname3MouseClicked

    private void hname4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hname4MouseClicked
        // TODO add your handling code here:
        selected_hotel=hname4.getText();
        String loc=location.place.toLowerCase();
        code=loc.substring(0,3);
        hotel_display x = new hotel_display();
        this.setVisible(false);
        x.setVisible(true);
    }//GEN-LAST:event_hname4MouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        login a =new login();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new bookl().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel hname1;
    private javax.swing.JLabel hname2;
    private javax.swing.JLabel hname3;
    private javax.swing.JLabel hname4;
    private javax.swing.JLabel im1;
    private javax.swing.JLabel im2;
    private javax.swing.JLabel im3;
    private javax.swing.JPanel im4;
    private javax.swing.JLabel im5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton logout;
    private javax.swing.JLabel nrate1;
    private javax.swing.JLabel nrate2;
    private javax.swing.JLabel nrate3;
    private javax.swing.JLabel nrate4;
    private javax.swing.JLabel price1;
    private javax.swing.JLabel price2;
    private javax.swing.JLabel price3;
    private javax.swing.JLabel price4;
    private javax.swing.JLabel rate1;
    private javax.swing.JLabel rate2;
    private javax.swing.JLabel rate3;
    private javax.swing.JLabel rate4;
    private javax.swing.JLabel sname;
    private javax.swing.JComboBox sort;
    private javax.swing.JLabel splace;
    private javax.swing.JLabel trr;
    // End of variables declaration//GEN-END:variables
}
